Repository GEOS-ESM/GEOSgcm, pull requests merged in 2019-09, with the labels that each got.

#50 Fixes #49. Corrects GFIO build bug
  Develop.cfg
  Externals.cfg
Labels: 0 diff trivial

#51 Update README.md
  README.md
Labels: 0 diff trivial, documentation

#52 Update CPLFCST_Etc version to fix .git copy
  Develop.cfg
  Externals.cfg
Labels: 0 diff trivial

#54 Manually merge master into dev/MAPL-2.0 to create history and update
  .circleci/config.yml
  .github/CODEOWNERS
  CMakeLists.txt
  Develop.cfg
  Externals.cfg
  README.md
  src/Shared/.gitignore
  src/Shared/CMakeLists.txt
Labels: 0 diff

#56 Update to ESMA_env 1.3.3
  Develop.cfg
Labels: 0 diff trivial

#53 Add GSW-Fortran to Shared libraries
  Develop.cfg
  Externals.cfg
  src/Shared/.gitignore
  src/Shared/CMakeLists.txt
Labels: 0 diff structural

#58 Update config.yml
  .circleci/config.yml
Labels: 0 diff structural

#57 Update Develop.cfg
  Develop.cfg
Labels: 0 diff structural

#59 This only updates MAPL to version 1.1.9. Needed for fixing issue #82 …
  Develop.cfg
Labels: 0 diff

#60 Update FMS to geos/orphan/1.0.1
  Develop.cfg
Labels: 0 diff

#62 Update to ESMA_env 1.4.0
  Develop.cfg
Labels: 0 diff

#63 Update Develop.cfg
  Develop.cfg
Labels: 0 diff
