Repository GEOS-ESM/GEOSgcm, pull requests merged in 2019-10, with the labels that each got.

#64 Fixes #75. Rename GFDL_fms to fms. Update cmake
  Develop.cfg
  src/Shared/.gitignore
  src/Shared/CMakeLists.txt
Labels: 0 diff structural

#66 Update Externals.cfg to match Develop.cfg
  Externals.cfg
Labels: 0 diff

#65 Added and editted the Changelog
  ChangeLog
Labels: 0 diff trivial

#70 Update Develop.cfg
  Develop.cfg
Labels: 0 diff trivial
