Repository GEOS-ESM/GEOSgcm, pull requests merged in 2020-11, with the labels that each got.

#220 Update CHANGELOG for 10.16.3 release
  CHANGELOG.md
  CMakeLists.txt
Labels: 0 diff trivial, documentation

#221 Update NCEP_Shared to v1.1.0
  Develop.cfg
  Externals.cfg
  components.yaml
Labels: 0 diff

#222 Update FMS: Fix for flush issue on macOS
  Develop.cfg
  Externals.cfg
  components.yaml
Labels: 0 diff, bugfix

#223 Update to MAPL 2.3.6
  Develop.cfg
  Externals.cfg
  components.yaml
Labels: 0 diff

#225 Fix bug in parallel_build
  parallel_build.csh
Labels: 0 diff, bugfix

#226 Move to ESMA_env v3.1.0
  Develop.cfg
  Externals.cfg
  components.yaml
Labels: 0 diff

#229 Update to MAPL 2.4.0 and ESMA_cmake 3.3.0
  Develop.cfg
  Externals.cfg
  components.yaml
Labels: 0 diff

#228 Update CI to 6.0.22
  .circleci/config.yml
  .github/workflows/workflow.yml
Labels: 0 diff structural, 0 diff trivial

#227 add NCEP_bufr to turn on BUILD_SHARED_LIBS
  .circleci/config.yml
  .github/workflows/workflow.yml
  Develop.cfg
  Externals.cfg
  components.yaml
  config/NCEP_Shared.sparse
Labels: 0 diff

#230 Remove support for manage_externals
  Develop.cfg
  Externals.cfg
  README.md
  components.yaml
  parallel_build.csh
Labels: 0 diff

#231 Updates for next release
  CHANGELOG.md
  CMakeLists.txt
Labels: 0 diff trivial

#232 Degrade CircleCI to medium
  .circleci/config.yml
Labels: 0 diff, 0 diff trivial, enhancement
