Repository GEOS-ESM/GEOSgcm, pull requests merged in 2020-03, with the labels that each got.

#117 Move to MAPL v2.0.1
  Develop.cfg
  Externals.cfg
  components.yaml
Labels: 0 diff

#118 Updates for release v10.11.0
  CHANGELOG.md
  Develop.cfg
  Externals.cfg
  components.yaml
Labels: Non 0-diff

#119 Update components.yaml env and cmake aliases
  components.yaml
Labels: 0 diff structural

#120 Update model version number
  CMakeLists.txt
Labels: 0 diff trivial

#122 Use relative URLs for GEOS-ESM packages
  components.yaml
Labels: 0 diff structural, enhancement

#123 Update to 10.12.0
  CMakeLists.txt
  Externals.cfg
  components.yaml
Labels: Non 0-diff

#124 Update CHANGELOG.md
  CHANGELOG.md
Labels: 0 diff trivial

#126 Fixes #125. Move to MAPL v2.0.2
  Develop.cfg
  Externals.cfg
  components.yaml
Labels: 0 diff

#129 Add SLES 12 note for module files
  README.md
Labels: 0 diff trivial

#128 Use https url for GSW
  components.yaml
Labels: 0 diff structural

#127 Update to ESMA_env v2.0.4
  Develop.cfg
  Externals.cfg
  components.yaml
Labels: 0 diff structural

#130 Updates to externals/components
  Develop.cfg
  Externals.cfg
  components.yaml
Labels: 0 diff

#131 Uptick to release v10.12.1
  CHANGELOG.md
  CMakeLists.txt
  Externals.cfg
  components.yaml
Labels: 0 diff
