Repository GEOS-ESM/GEOSgcm, pull requests merged in 2020-01, with the labels that each got.

#78 Update Externals.cfg to sync with develop
  Externals.cfg
Labels: 0 diff

#79 Update to UMD_Etc v1.0.2
  Develop.cfg
Labels: 0 diff trivial

#80 Update Externals.cfg
  CHANGELOG.md
  Externals.cfg
Labels: 0 diff trivial

#81 Updates for Develop: MAPL & FMS
  Develop.cfg
Labels: 0 diff

#82 Update components.yaml
  components.yaml
Labels: 0 diff

#77 Added components.yaml in preparation for mepo
  components.yaml
Labels: 0 diff structural, 0 diff trivial

#83 Update to ESMA_env v1.4.1
  Develop.cfg
  Externals.cfg
Labels: 0 diff

#85 Update Externals.cfg to Develop.cfg
  Externals.cfg
Labels: Non 0-diff

#87 Update CHANGELOG.md
  CHANGELOG.md
Labels: 0 diff trivial

#89 Update Externals.cfg
  Develop.cfg
  Externals.cfg
Labels: 0 diff, Non 0-diff

#91 Update components.yaml
  components.yaml
Labels: 0 diff

#92 Update Externals.cfg
  Externals.cfg
  components.yaml
Labels: 0 diff, enhancement

#93 Update CHANGELOG.md
  CHANGELOG.md
Labels: 0 diff trivial, documentation

#96 Update Develop.cfg
  Develop.cfg
  components.yaml
Labels: Non 0-diff

#97 Sync develop into master
  CHANGELOG.md
  Externals.cfg
  components.yaml
Labels: Non 0-diff
