Repository GEOS-ESM/GEOSgcm, pull requests merged in 2020-09, with the labels that each got.

#194 Update MOM6 to v1.1.0
  components.yaml
Labels: 0 diff structural

#198 Uptick GMAO_Shared
  Develop.cfg
  Externals.cfg
  components.yaml
Labels: 0 diff trivial, enhancement

#196 Add AWS CodeBuild file
  .codebuild/buildspec.yml
  .github/CODEOWNERS
  README.md
Labels: 0 diff structural, enhancement

#197 Update FVdycoreCubed_GridComp to v1.2.5
  components.yaml
Labels: 0 diff, 0 diff trivial, enhancement

#199 Update README.md with CI Table
  README.md
Labels: 0 diff trivial, documentation

#200 Update the CircleCI image
  .circleci/config.yml
Labels: 0 diff trivial

#201 Update to ESMA_cmake v3.1.4
  Develop.cfg
  Externals.cfg
  components.yaml
Labels: 0 diff

#202 Update to ESMA_cmake 3.2.0 and NCEP_Shared 1.0.1
  Develop.cfg
  Externals.cfg
  components.yaml
Labels: 0 diff

#203 Uptick components
  CHANGELOG.md
  CMakeLists.txt
  Develop.cfg
  Externals.cfg
  components.yaml
Labels: 0 diff

#195 Move to use Intel 19.1.2
  Develop.cfg
  Externals.cfg
  components.yaml
Labels: Non 0-diff

#204 Update to v10.15.0
  CHANGELOG.md
  CMakeLists.txt
  Develop.cfg
  Externals.cfg
  components.yaml
Labels: Non 0-diff

#205 Uptick GEOSgcm Release
  CHANGELOG.md
  CMakeLists.txt
  Develop.cfg
  Externals.cfg
  components.yaml
Labels: Non 0-diff, bugfix

#206 Update to ESMA_cmake v3.2.1
  Develop.cfg
  Externals.cfg
  components.yaml
Labels: 0 diff
