Repository GEOS-ESM/GEOSgcm, pull requests merged in 2020-05, with the labels that each got.

#145 Update to MAPL v2.1.3
  .circleci/config.yml
  .github/CODEOWNERS
  Develop.cfg
  Externals.cfg
  components.yaml
Labels: 0 diff

#146 Update to release v10.12.4
  CHANGELOG.md
  CMakeLists.txt
  Externals.cfg
  components.yaml
Labels: 0 diff

#148 Update to GCM GC 1.8.5 and FV3 1.1.1
  Externals.cfg
  components.yaml
Labels: 0 diff, bugfix

#147 Update ESMA_env, ESMA_cmake, and MAPL
  Develop.cfg
  Externals.cfg
  components.yaml
Labels: 0 diff structural, enhancement

#149 Move to use Baselibs 6.0.13 in CI
  .circleci/config.yml
Labels: 0 diff structural
