Repository GEOS-ESM/GEOSgcm, pull requests merged in 2020-07, with the labels that each got.

#169 Update GMAO_Shared to v1.1.6
  Develop.cfg
  Externals.cfg
  components.yaml
Labels: 0 diff

#171 Update README.md
  README.md
Labels: 0 diff trivial, documentation

#170 Additional CMake Updates for JEDI Compatibility
  Develop.cfg
  Externals.cfg
  components.yaml
Labels: 0 diff

#173 Update FMS to geos/2019.01.02+noaff
  Develop.cfg
  Externals.cfg
  components.yaml
Labels: 0 diff

#174 Update to ESMA_cmake v3.0.7
  .gitignore
  Develop.cfg
  Externals.cfg
  components.yaml
Labels: 0 diff

#161 Sparse out Pilgrim, FV, ARIES
  Develop.cfg
  Externals.cfg
  components.yaml
  config/GEOSgcm_GridComp.sparse
  config/GMAO_Shared.sparse
Labels: 0 diff structural

#172 Add MOM6
  Externals.cfg
  components.yaml
Labels: 0 diff, enhancement

#176 Uptick GEOSgcm to v10.14.0
  CHANGELOG.md
  CMakeLists.txt
Labels: 0 diff

#179 Fixes #177: Updates to fix GNU build for MOM5/MOM6 issue
  Externals.cfg
  components.yaml
Labels: 0 diff, bugfix

#180 Update to FV3 GC v1.2.0
  components.yaml
Labels: 0 diff

#181 Updates for next release
  CHANGELOG.md
  CMakeLists.txt
  Develop.cfg
  Externals.cfg
  components.yaml
Labels: 0 diff, bugfix, enhancement

#182 Update to ESMA_cmake v3.1.1
  Develop.cfg
  Externals.cfg
  components.yaml
Labels: 0 diff
