Repository GEOS-ESM/GEOSgcm, pull requests merged in 2020-10, with the labels that each got.

#210 Uptick GMAO_Shared
  Develop.cfg
  Externals.cfg
  components.yaml
Labels: 0 diff

#207 Update MAPL to v2.3.2
  Develop.cfg
  Externals.cfg
  components.yaml
Labels: 0 diff

#212 Uptick GMAO_Shared
  Develop.cfg
  Externals.cfg
  components.yaml
Labels: 0 diff

#211 Update to ESMA_env v3.0.1
  Develop.cfg
  Externals.cfg
  components.yaml
Labels: 0 diff structural, 0 diff trivial

#213 Update MAPL to v2.3.3
  Develop.cfg
  Externals.cfg
  components.yaml
Labels: 0 diff

#209 Add Github CI
  .github/workflows/workflow.yml
Labels: 0 diff structural, 0 diff trivial

#214 Uptick gcm
  CHANGELOG.md
  CMakeLists.txt
  Externals.cfg
  components.yaml
Labels: 0 diff

#215 Add Docker authentication for pulls
  .circleci/config.yml
  .github/workflows/workflow.yml
  README.md
Labels: 0 diff structural

#216 Update MAPL to v2.3.4
  Develop.cfg
  Externals.cfg
  components.yaml
Labels: 0 diff

#217 Uptick gcm for new release
  CHANGELOG.md
  CMakeLists.txt
  Develop.cfg
  Externals.cfg
  components.yaml
Labels: 0 diff

#219 Update components to monitor fixture
  components.yaml
Labels: 0 diff, enhancement
