Repository GEOS-ESM/GEOSgcm, pull requests merged in 2021-07, with the labels that each got.

#305 Update to NCEP_Shared v1.2.0
  README.md
  components.yaml
Labels: 0 diff

#306 Update CI to be more logical
  .circleci/config.yml
  .codebuild/buildspec.yml
  .github/workflows/workflow.yml
Labels: 0 diff

#307 Minor update to GOCART components entry
  components.yaml
Labels: 0 diff trivial

#308 Update to GMAO_Shared v1.4.5
  README.md
  components.yaml
Labels: 0 diff

#309 Update ESMA_cmake to v3.5.2
  README.md
  components.yaml
Labels: 0 diff, 0 diff structural

#313 Update to fvdycore v1.1.7
  README.md
  components.yaml
Labels: 0 diff

#312 Update MAPL to 2.8.0
  README.md
  components.yaml
Labels: 0 diff, Non 0-diff

#310 Add GCM run to CI
  .circleci/config.yml
Labels: 0 diff

#314 Uptick to v10.19.3
  CHANGELOG.md
  CMakeLists.txt
  components.yaml
Labels: 0 diff
