Repository GEOS-ESM/GEOSgcm, pull requests merged in 2021-12, with the labels that each got.

#355 Update to ESMA_env v3.7.0
  README.md
  components.yaml
Labels: 0 diff

#356 Update to MAPL 2.13.0
  README.md
  components.yaml
Labels: 0 diff

#358 Uptick gcm
  CHANGELOG.md
  CMakeLists.txt
  README.md
  components.yaml
Labels: 0 diff

#359 Update CODEOWNERS
  .github/CODEOWNERS
Labels: 0 diff trivial

#361 Update to MAPL 2.14.0
  README.md
  components.yaml
Labels: 0 diff

#357 Update to fvdycore geos/v1.3.0, FV3 GC v1.4.1, GMAO_Shared v1.5.0, GCM GC v1.13.0, Chem v1.7.0
  README.md
  components.yaml
Labels: Non 0-diff

#360 Update to ESMA_cmake v3.8.0 and ESMA_env v3.8.0
  .circleci/config.yml
  README.md
  components.yaml
Labels: Non 0-diff

#362 Uptick to GCM v10.20.0
  CHANGELOG.md
  CMakeLists.txt
Labels: 0 diff trivial

#365 Updates for GEOSgcm v10.21.0
  CHANGELOG.md
  CMakeLists.txt
  README.md
  components.yaml
Labels: Non 0-diff

#363 Updates for Rome nodes at NAS
  README.md
  components.yaml
Labels: 0 diff

#364 Update to MAPL 2.14.1
  README.md
  components.yaml
Labels: 0 diff
