Repository GEOS-ESM/GEOSgcm, pull requests merged in 2022-03, with the labels that each got.

#386 Remove GOCART.sparse file
  config/GOCART.sparse
Labels: 0 diff trivial

#391 Uptick to v10.22.0
  CHANGELOG.md
  CMakeLists.txt
  README.md
  components.yaml
Labels: Non 0-diff

#393 Update to MAPL 2.18.3, ESMA_cmake 3.12, ESMA_env 3.13
  .circleci/config.yml
  README.md
  components.yaml
Labels: 0 diff

#379 Fixes #377. Split Ocean Grid Comp into new repo
  README.md
  components.yaml
Labels: 0 diff trivial, 0 diff, 0 diff structural

#385 Add new sea ice model
  components.yaml
Labels: enhancement, 0 diff structural

#394 Fixes #387. Updates for Spack Support
  README.md
  components.yaml
Labels: 0 diff

#397 Update GEOSchem_GridComp to v1.9.1
  CHANGELOG.md
  CMakeLists.txt
  README.md
  components.yaml
Labels: 0 diff

#400 Change develop branch of MOM6 to main
  components.yaml
Labels: 0 diff trivial, 0 diff structural

#404 Update to MAPL 2.19.1
  README.md
  components.yaml
Labels: 0 diff

#403 Update CI to use v1 orb and job
  .circleci/config.yml
Labels: 0 diff trivial

#402 Update MOM6 and GEOS_OceanGridComp
  README.md
  components.yaml
Labels: enhancement, 0 diff, Non 0-diff
