Repository GEOS-ESM/GEOSgcm, pull requests merged in 2023-11, with the labels that each got.

#694 Update to GMAO_Shared v1.9.6
  README.md
  components.yaml
Labels: 0 diff

#696 Update to fvdycore geos/v2.7.0
  README.md
  components.yaml
Labels: 0 diff

#693 Update CI BCs to v11.3.0
  .circleci/config.yml
Labels: 0 diff

#698 Update to NCEP_Shared v1.3.0
  README.md
  components.yaml
Labels: 0 diff trivial

#701 Update to FVdycoreCubed_GridComp v2.9.0
  README.md
  components.yaml
Labels: 0 diff

#706 Update MOM and OceanGC
  README.md
  components.yaml
Labels: 0 diff structural

#702 update cice6 to geos/v0.1.3
  README.md
  components.yaml
Labels: 0 diff

#705 Update to Baselibs 7.15.1
  README.md
  components.yaml
Labels: 0 diff

#707 Update to fvdycore geos/v2.8.0
  README.md
  components.yaml
Labels: 0 diff
