Repository GEOS-ESM/GEOSgcm, pull requests merged in 2023-01, with the labels that each got.

#504 Uptick GEOS_OceanGridComp to v.2.1
  README.md
  components.yaml
Labels: 0 diff structural

#505 Add custom messages to label enforcers
  .github/workflows/enforce-labels.yml
Labels: 0 diff trivial

#507 Update to MAPL 2.34.0, ESMA_cmake 3.24.0
  README.md
  components.yaml
Labels: 0 diff

#511 Advance Chemistry to v1.11.0
  README.md
  components.yaml
Labels: 0 diff

#514 Uptick to v10.23.3
  CHANGELOG.md
  CMakeLists.txt
  README.md
  components.yaml
Labels: 0 diff

#509 Move TR, GMI, and StratChem to separate repos
  CHANGELOG.md
  CMakeLists.txt
  README.md
  components.yaml
Labels: 0 diff structural
