Repository GEOS-ESM/GEOSgcm, pull requests merged in 2024-06, with the labels that each got.

#785 Updates for v12 branch for FMS-in-Baselibs
  .circleci/config.yml
  .github/workflows/workflow.yml
  CMakeLists.txt
  README.md
  components.yaml
Labels: Contingent - DNA, Non 0-diff

#788 Update Radiation GC to more stable branch
  components.yaml
Labels: 0 diff

#779 udpate CICE6 to post v6.5.0
  .circleci/config.yml
  README.md
  components.yaml
Labels: 0 diff

#790 [skip ci] Update for release v11.6.0
  CHANGELOG.md
  CMakeLists.txt
Labels: 0 diff trivial

#793 Update ESMA_cmake to v3.46.0
  README.md
  components.yaml
Labels: 0 diff
