Repository GEOS-ESM/GEOSgcm, pull requests merged in 2024-01, with the labels that each got.

#719 Update to MAPL 2.43.0
  .circleci/config.yml
  README.md
  components.yaml
Labels: 0 diff

#722 Update to GEOSradiation_GridComp v1.6.0
  README.md
  components.yaml
Labels: 0 diff

#731 Uptick GCM to v11.5.0
  CHANGELOG.md
  CMakeLists.txt
  README.md
  components.yaml
Labels: Non 0-diff

#729 Update to ESMA_cmake v3.38.0
  README.md
  components.yaml
Labels: 0 diff

#724 Integrate WMMA
  README.md
  components.yaml
Labels: enhancement, 0 diff structural

#737 Update to MAPL 2.43.1
  README.md
  components.yaml
Labels: 0 diff

#740 Uptick to v11.5.1
  CHANGELOG.md
  CMakeLists.txt
  README.md
Labels: 0 diff trivial
