Repository GEOS-ESM/GEOSgcm, pull requests merged in 2025-01, with the labels that each got.

#863 v11: Update to ESMA_cmake v3.56.0, FV3 GC v2.13.0, ESMA_env v4.29.2
  README.md
  components.yaml
Labels: 0 diff

#866 Add Gigatraj Support
  README.md
  components.yaml
Labels: 0 diff

#868 [skip ci] Uptick to GCM v11.6.3
  CHANGELOG.md
  CMakeLists.txt
Labels: 0 diff trivial

#803 v11: Update to GOCART v2.3.0, Chem v1.15.0
  README.md
  components.yaml
Labels: Non 0-diff

#804 v11: Update to ESMA_env v4.34.0
  README.md
  components.yaml
  parallel_build.csh
Labels: 0 diff, Non 0-diff

#871 v11: Update to MAPL 2.52.0
  CMakeLists.txt
  README.md
  components.yaml
Labels: 0 diff

#872 v11: Update to HEMCO geos/v2.3.0
  README.md
  components.yaml
Labels: Non 0-diff

#878 Update to App v2.3.8, GC v2.7.0, Util v2.1.6
  .circleci/config.yml
  .github/workflows/workflow.yml
  README.md
  components.yaml
Labels: Non 0-diff

#880 [skip ci] Uptick to v11.7.0
  CHANGELOG.md
  CMakeLists.txt
Labels: 0 diff trivial
