Repository GEOS-ESM/GEOSgcm, pull requests merged in 2025-09, with the labels that each got.

#968 [skip ci] Uptick to v11.7.3 tag
  CHANGELOG.md
  CMakeLists.txt
Labels: 0 diff trivial

#962 v11: Update to Baselibs 8.18.0, ESMA_cmake v3.64.0
  .circleci/config.yml
  .github/workflows/workflow.yml
  README.md
  components.yaml
Labels: 0 diff

#967 v12: Update to Baselibs 8.18.0, ESMA_cmake v4.22.0
  .circleci/config.yml
  .github/workflows/release-tarball.yml
  .github/workflows/spack-ci.yml
  .github/workflows/workflow.yml
  CHANGELOG.md
  README.md
  components.yaml
Labels: 0 diff

#974 v12: Update to MAPL 2.60.0
  CMakeLists.txt
  README.md
  components.yaml
Labels: 0 diff, Non 0-diff

#888 v11: added topo component
  CHANGELOG.md
  README.md
  components.yaml
Labels: 0 diff

#977 v11: Update to MAPL 2.59.1
  README.md
  components.yaml
Labels: 0 diff
