Repository GEOS-ESM/GEOSgcm, pull requests merged in 2025-02, with the labels that each got.

#864 v12: Update to ESMA_cmake v4.12.0, ESMA_env 5.7.1
  .circleci/config.yml
  .github/workflows/workflow.yml
  README.md
  components.yaml
Labels: Non 0-diff

#885 v11: Update to MAPL 2.54.1
  CMakeLists.txt
  README.md
  components.yaml
Labels: 0 diff

#893 v11: Update to Baselibs 7.32.0
  README.md
  components.yaml
Labels: 0 diff

#886 v11: Update to GEOSradiation_GridComp v1.11.0
  README.md
  components.yaml
Labels: 0 diff

#873 v12: Update README for HEMCO geos/v2.3.0
  .circleci/config.yml
  .github/workflows/workflow.yml
  README.md
Labels: Non 0-diff

#889 Update WAVEWATCH
  README.md
  components.yaml
Labels: enhancement, 0 diff

#900 Uptick App + GC
  README.md
  components.yaml
Labels: 0 diff
